[package]
name = "louis-parser"
version = "0.1.0"
authors = ["Christian Egli <christian.egli@sbs.ch>"]
edition = "2018"

[dependencies]
pest = "2.5.5"
pest_derive = "2.5.5"

[dev-dependencies]
claim = "0.5.0"
